spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/home-hair
    username: sa
    password:
    driver-class-name: org.h2.Driver

  output:
    ansi:
      enabled: ALWAYS
